import './Delivery.css'

export default function Delivery() {
    return (
        <main className='delivery'>
            <h2>Shipping & Delivery</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at elit erat, vitae rutrum lectus. In vitae sem rutrum velit pulvinar ultricies sed ac enim. Curabitur eu risus vitae felis facilisis malesuada quis nec mauris. Donec sit amet leo lobortis libero sollicitudin rutrum non at enim. Sed suscipit, felis bibendum malesuada cursus, odio lorem convallis orci, sit amet dictum nibh diam vitae sapien. Ut sed lobortis ipsum. Nam adipiscing, eros fringilla condimentum sodales, leo dui hendrerit metus, sed blandit lorem nunc vel nunc. Aliquam a tincidunt quam. Sed consectetur molestie elit, at consectetur arcu vehicula ut. Ut ante nibh, vehicula quis volutpat ut, lacinia eu tortor.</p>
            <p>Donec a tortor orci. Sed leo libero, tincidunt non dapibus et, tristique in lorem. Ut risus magna, imperdiet at tempus vitae, placerat eu tortor. Nulla facilisi. Etiam quis neque lacus, eu vulputate tellus. Nullam a diam scelerisque dui egestas adipiscing. Donec auctor ligula lorem. Pellentesque commodo, enim id cursus aliquam, nibh felis hendrerit justo, sed auctor dui magna id nisi. Duis nec auctor erat. Integer fringilla, mauris non scelerisque egestas, neque augue mollis eros, eget placerat nibh magna quis elit. Duis in adipiscing nibh. Donec scelerisque, enim in varius feugiat, est odio dignissim justo, ac dictum ligula massa at justo. Nulla facilisi. Sed vitae molestie ipsum. Sed commodo tempus justo hendrerit pulvinar. Maecenas commodo, leo id consequat volutpat, mauris sem facilisis nulla, faucibus ullamcorper quam risus et mi. Suspendisse et viverra lorem.</p>
            <p>Sed convallis felis vitae libero ullamcorper a sollicitudin risus venenatis. Suspendisse ultrices vulputate porttitor. Nunc sagittis est sed elit convallis sit amet vulputate dui sollicitudin. Nulla vitae turpis elit. Fusce gravida tincidunt urna eu pulvinar. Aenean eu lectus risus, lacinia ullamcorper magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc in odio nibh, nec fermentum dolor. Vivamus in sapien eget mauris eleifend vulputate sit amet et magna. Phasellus ut nulla eget massa consectetur consectetur. Cras suscipit nulla et mauris rutrum mattis sollicitudin ipsum porttitor. Donec luctus lobortis dui, non ultrices eros eleifend vel. Fusce sit amet enim in elit consequat bibendum id sed mauris. Sed aliquet varius molestie. Morbi semper mattis odio eget ullamcorper.</p>
        </main>
    )
}
